/*
 * generated by Xtext 2.23.0
 */
package accesses.accesses.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAccessesScopeProvider extends DelegatingScopeProvider {
}
