/**
 * generated by Xtext 2.23.0
 */
package ontological.ontological.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import ontological.ontological.services.OntologicalGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class OntologicalFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private OntologicalGrammarAccess _ontologicalGrammarAccess;

  protected void _format(final /* OntologicalRoot */Object ontologicalRoot, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nontologicalRoot cannot be resolved"
      + "\nformat cannot be resolved");
  }

  protected void _format(final /* OntologicalRootClasses */Object ontologicalRootClasses, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nclasses cannot be resolved"
      + "\nformat cannot be resolved");
  }

  public void format(final Object ontologicalRoot, final IFormattableDocument document) {
    if (ontologicalRoot instanceof XtextResource) {
      _format((XtextResource)ontologicalRoot, document);
      return;
    } else if (ontologicalRoot instanceof EObject) {
      _format((EObject)ontologicalRoot, document);
      return;
    } else if (ontologicalRoot == null) {
      _format((Void)null, document);
      return;
    } else if (ontologicalRoot != null) {
      _format(ontologicalRoot, document);
      return;
    } else if (ontologicalRoot != null) {
      _format(ontologicalRoot, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(ontologicalRoot, document).toString());
    }
  }
}
