/*
 * generated by Xtext 2.23.0
 */
package accesses.accesses.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AccessesAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("accesses/accesses/parser/antlr/internal/InternalAccessesParser.tokens");
	}
}
