/*
 * generated by Xtext 2.23.0
 */
package graphic.graphic.ui;

import com.google.inject.Injector;
import graphic.graphic.ui.internal.GraphicActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GraphicExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(GraphicActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		GraphicActivator activator = GraphicActivator.getInstance();
		return activator != null ? activator.getInjector(GraphicActivator.GRAPHIC_GRAPHIC_GRAPHIC) : null;
	}

}
