/**
 */
package graphic.provider;

import graphic.util.GraphicAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class GraphicItemProviderAdapterFactory extends GraphicAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public GraphicItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRoot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootItemProvider graphicRootItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRoot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootAdapter() {
		if (graphicRootItemProvider == null) {
			graphicRootItemProvider = new GraphicRootItemProvider(this);
		}

		return graphicRootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootName} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootNameItemProvider graphicRootNameItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootName}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootNameAdapter() {
		if (graphicRootNameItemProvider == null) {
			graphicRootNameItemProvider = new GraphicRootNameItemProvider(this);
		}

		return graphicRootNameItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootURI} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootURIItemProvider graphicRootURIItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootURI}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootURIAdapter() {
		if (graphicRootURIItemProvider == null) {
			graphicRootURIItemProvider = new GraphicRootURIItemProvider(this);
		}

		return graphicRootURIItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClasses} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemProvider graphicRootClassesItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClasses}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesAdapter() {
		if (graphicRootClassesItemProvider == null) {
			graphicRootClassesItemProvider = new GraphicRootClassesItemProvider(this);
		}

		return graphicRootClassesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItems} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsItemProvider graphicRootClassesItemsItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItems}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsAdapter() {
		if (graphicRootClassesItemsItemProvider == null) {
			graphicRootClassesItemsItemProvider = new GraphicRootClassesItemsItemProvider(this);
		}

		return graphicRootClassesItemsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsName} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsNameItemProvider graphicRootClassesItemsNameItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsName}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsNameAdapter() {
		if (graphicRootClassesItemsNameItemProvider == null) {
			graphicRootClassesItemsNameItemProvider = new GraphicRootClassesItemsNameItemProvider(this);
		}

		return graphicRootClassesItemsNameItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsVersions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsVersionsItemProvider graphicRootClassesItemsVersionsItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsVersions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsVersionsAdapter() {
		if (graphicRootClassesItemsVersionsItemProvider == null) {
			graphicRootClassesItemsVersionsItemProvider = new GraphicRootClassesItemsVersionsItemProvider(this);
		}

		return graphicRootClassesItemsVersionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsVersionsV1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsVersionsV1ItemProvider graphicRootClassesItemsVersionsV1ItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsVersionsV1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsVersionsV1Adapter() {
		if (graphicRootClassesItemsVersionsV1ItemProvider == null) {
			graphicRootClassesItemsVersionsV1ItemProvider = new GraphicRootClassesItemsVersionsV1ItemProvider(this);
		}

		return graphicRootClassesItemsVersionsV1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsVersionsV2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsVersionsV2ItemProvider graphicRootClassesItemsVersionsV2ItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsVersionsV2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsVersionsV2Adapter() {
		if (graphicRootClassesItemsVersionsV2ItemProvider == null) {
			graphicRootClassesItemsVersionsV2ItemProvider = new GraphicRootClassesItemsVersionsV2ItemProvider(this);
		}

		return graphicRootClassesItemsVersionsV2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsVersionsV3} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsVersionsV3ItemProvider graphicRootClassesItemsVersionsV3ItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsVersionsV3}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsVersionsV3Adapter() {
		if (graphicRootClassesItemsVersionsV3ItemProvider == null) {
			graphicRootClassesItemsVersionsV3ItemProvider = new GraphicRootClassesItemsVersionsV3ItemProvider(this);
		}

		return graphicRootClassesItemsVersionsV3ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsVname} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsVnameItemProvider graphicRootClassesItemsVnameItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsVname}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsVnameAdapter() {
		if (graphicRootClassesItemsVnameItemProvider == null) {
			graphicRootClassesItemsVnameItemProvider = new GraphicRootClassesItemsVnameItemProvider(this);
		}

		return graphicRootClassesItemsVnameItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsVnameV1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsVnameV1ItemProvider graphicRootClassesItemsVnameV1ItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsVnameV1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsVnameV1Adapter() {
		if (graphicRootClassesItemsVnameV1ItemProvider == null) {
			graphicRootClassesItemsVnameV1ItemProvider = new GraphicRootClassesItemsVnameV1ItemProvider(this);
		}

		return graphicRootClassesItemsVnameV1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsVnameV2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsVnameV2ItemProvider graphicRootClassesItemsVnameV2ItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsVnameV2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsVnameV2Adapter() {
		if (graphicRootClassesItemsVnameV2ItemProvider == null) {
			graphicRootClassesItemsVnameV2ItemProvider = new GraphicRootClassesItemsVnameV2ItemProvider(this);
		}

		return graphicRootClassesItemsVnameV2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsVnameV3} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsVnameV3ItemProvider graphicRootClassesItemsVnameV3ItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsVnameV3}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsVnameV3Adapter() {
		if (graphicRootClassesItemsVnameV3ItemProvider == null) {
			graphicRootClassesItemsVnameV3ItemProvider = new GraphicRootClassesItemsVnameV3ItemProvider(this);
		}

		return graphicRootClassesItemsVnameV3ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsShowAttributes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsShowAttributesItemProvider graphicRootClassesItemsShowAttributesItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsShowAttributes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsShowAttributesAdapter() {
		if (graphicRootClassesItemsShowAttributesItemProvider == null) {
			graphicRootClassesItemsShowAttributesItemProvider = new GraphicRootClassesItemsShowAttributesItemProvider(this);
		}

		return graphicRootClassesItemsShowAttributesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsShowAttributesItems} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsShowAttributesItemsItemProvider graphicRootClassesItemsShowAttributesItemsItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsShowAttributesItems}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsShowAttributesItemsAdapter() {
		if (graphicRootClassesItemsShowAttributesItemsItemProvider == null) {
			graphicRootClassesItemsShowAttributesItemsItemProvider = new GraphicRootClassesItemsShowAttributesItemsItemProvider(this);
		}

		return graphicRootClassesItemsShowAttributesItemsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsMaterialAttributes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsMaterialAttributesItemProvider graphicRootClassesItemsMaterialAttributesItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsMaterialAttributes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsMaterialAttributesAdapter() {
		if (graphicRootClassesItemsMaterialAttributesItemProvider == null) {
			graphicRootClassesItemsMaterialAttributesItemProvider = new GraphicRootClassesItemsMaterialAttributesItemProvider(this);
		}

		return graphicRootClassesItemsMaterialAttributesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsMaterialAttributesItems} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsMaterialAttributesItemsItemProvider graphicRootClassesItemsMaterialAttributesItemsItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsMaterialAttributesItems}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsMaterialAttributesItemsAdapter() {
		if (graphicRootClassesItemsMaterialAttributesItemsItemProvider == null) {
			graphicRootClassesItemsMaterialAttributesItemsItemProvider = new GraphicRootClassesItemsMaterialAttributesItemsItemProvider(this);
		}

		return graphicRootClassesItemsMaterialAttributesItemsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConstraints} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConstraintsItemProvider graphicRootClassesItemsConstraintsItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConstraints}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConstraintsAdapter() {
		if (graphicRootClassesItemsConstraintsItemProvider == null) {
			graphicRootClassesItemsConstraintsItemProvider = new GraphicRootClassesItemsConstraintsItemProvider(this);
		}

		return graphicRootClassesItemsConstraintsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConstraintsPlanes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConstraintsPlanesItemProvider graphicRootClassesItemsConstraintsPlanesItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConstraintsPlanes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConstraintsPlanesAdapter() {
		if (graphicRootClassesItemsConstraintsPlanesItemProvider == null) {
			graphicRootClassesItemsConstraintsPlanesItemProvider = new GraphicRootClassesItemsConstraintsPlanesItemProvider(this);
		}

		return graphicRootClassesItemsConstraintsPlanesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConstraintsIlumination} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConstraintsIluminationItemProvider graphicRootClassesItemsConstraintsIluminationItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConstraintsIlumination}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConstraintsIluminationAdapter() {
		if (graphicRootClassesItemsConstraintsIluminationItemProvider == null) {
			graphicRootClassesItemsConstraintsIluminationItemProvider = new GraphicRootClassesItemsConstraintsIluminationItemProvider(this);
		}

		return graphicRootClassesItemsConstraintsIluminationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConstraintsSizeMax} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConstraintsSizeMaxItemProvider graphicRootClassesItemsConstraintsSizeMaxItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConstraintsSizeMax}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConstraintsSizeMaxAdapter() {
		if (graphicRootClassesItemsConstraintsSizeMaxItemProvider == null) {
			graphicRootClassesItemsConstraintsSizeMaxItemProvider = new GraphicRootClassesItemsConstraintsSizeMaxItemProvider(this);
		}

		return graphicRootClassesItemsConstraintsSizeMaxItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConstraintsSizeMin} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConstraintsSizeMinItemProvider graphicRootClassesItemsConstraintsSizeMinItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConstraintsSizeMin}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConstraintsSizeMinAdapter() {
		if (graphicRootClassesItemsConstraintsSizeMinItemProvider == null) {
			graphicRootClassesItemsConstraintsSizeMinItemProvider = new GraphicRootClassesItemsConstraintsSizeMinItemProvider(this);
		}

		return graphicRootClassesItemsConstraintsSizeMinItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConstraintsSizeInit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConstraintsSizeInitItemProvider graphicRootClassesItemsConstraintsSizeInitItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConstraintsSizeInit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConstraintsSizeInitAdapter() {
		if (graphicRootClassesItemsConstraintsSizeInitItemProvider == null) {
			graphicRootClassesItemsConstraintsSizeInitItemProvider = new GraphicRootClassesItemsConstraintsSizeInitItemProvider(this);
		}

		return graphicRootClassesItemsConstraintsSizeInitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConstraintsOverlapping} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConstraintsOverlappingItemProvider graphicRootClassesItemsConstraintsOverlappingItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConstraintsOverlapping}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConstraintsOverlappingAdapter() {
		if (graphicRootClassesItemsConstraintsOverlappingItemProvider == null) {
			graphicRootClassesItemsConstraintsOverlappingItemProvider = new GraphicRootClassesItemsConstraintsOverlappingItemProvider(this);
		}

		return graphicRootClassesItemsConstraintsOverlappingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConstraintsXToOriginPos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConstraintsXToOriginPosItemProvider graphicRootClassesItemsConstraintsXToOriginPosItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConstraintsXToOriginPos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConstraintsXToOriginPosAdapter() {
		if (graphicRootClassesItemsConstraintsXToOriginPosItemProvider == null) {
			graphicRootClassesItemsConstraintsXToOriginPosItemProvider = new GraphicRootClassesItemsConstraintsXToOriginPosItemProvider(this);
		}

		return graphicRootClassesItemsConstraintsXToOriginPosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConstraintsYToOriginPos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConstraintsYToOriginPosItemProvider graphicRootClassesItemsConstraintsYToOriginPosItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConstraintsYToOriginPos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConstraintsYToOriginPosAdapter() {
		if (graphicRootClassesItemsConstraintsYToOriginPosItemProvider == null) {
			graphicRootClassesItemsConstraintsYToOriginPosItemProvider = new GraphicRootClassesItemsConstraintsYToOriginPosItemProvider(this);
		}

		return graphicRootClassesItemsConstraintsYToOriginPosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConstraintsZToOriginPos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConstraintsZToOriginPosItemProvider graphicRootClassesItemsConstraintsZToOriginPosItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConstraintsZToOriginPos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConstraintsZToOriginPosAdapter() {
		if (graphicRootClassesItemsConstraintsZToOriginPosItemProvider == null) {
			graphicRootClassesItemsConstraintsZToOriginPosItemProvider = new GraphicRootClassesItemsConstraintsZToOriginPosItemProvider(this);
		}

		return graphicRootClassesItemsConstraintsZToOriginPosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConstraintsRotation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConstraintsRotationItemProvider graphicRootClassesItemsConstraintsRotationItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConstraintsRotation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConstraintsRotationAdapter() {
		if (graphicRootClassesItemsConstraintsRotationItemProvider == null) {
			graphicRootClassesItemsConstraintsRotationItemProvider = new GraphicRootClassesItemsConstraintsRotationItemProvider(this);
		}

		return graphicRootClassesItemsConstraintsRotationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConstraintsText} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConstraintsTextItemProvider graphicRootClassesItemsConstraintsTextItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConstraintsText}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConstraintsTextAdapter() {
		if (graphicRootClassesItemsConstraintsTextItemProvider == null) {
			graphicRootClassesItemsConstraintsTextItemProvider = new GraphicRootClassesItemsConstraintsTextItemProvider(this);
		}

		return graphicRootClassesItemsConstraintsTextItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConstraintsTrim} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConstraintsTrimItemProvider graphicRootClassesItemsConstraintsTrimItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConstraintsTrim}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConstraintsTrimAdapter() {
		if (graphicRootClassesItemsConstraintsTrimItemProvider == null) {
			graphicRootClassesItemsConstraintsTrimItemProvider = new GraphicRootClassesItemsConstraintsTrimItemProvider(this);
		}

		return graphicRootClassesItemsConstraintsTrimItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConstraintsCategoryBitMask} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConstraintsCategoryBitMaskItemProvider graphicRootClassesItemsConstraintsCategoryBitMaskItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConstraintsCategoryBitMask}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConstraintsCategoryBitMaskAdapter() {
		if (graphicRootClassesItemsConstraintsCategoryBitMaskItemProvider == null) {
			graphicRootClassesItemsConstraintsCategoryBitMaskItemProvider = new GraphicRootClassesItemsConstraintsCategoryBitMaskItemProvider(this);
		}

		return graphicRootClassesItemsConstraintsCategoryBitMaskItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConstraintsCollisionBitMask} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConstraintsCollisionBitMaskItemProvider graphicRootClassesItemsConstraintsCollisionBitMaskItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConstraintsCollisionBitMask}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConstraintsCollisionBitMaskAdapter() {
		if (graphicRootClassesItemsConstraintsCollisionBitMaskItemProvider == null) {
			graphicRootClassesItemsConstraintsCollisionBitMaskItemProvider = new GraphicRootClassesItemsConstraintsCollisionBitMaskItemProvider(this);
		}

		return graphicRootClassesItemsConstraintsCollisionBitMaskItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConstraintsContactTestBitMask} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConstraintsContactTestBitMaskItemProvider graphicRootClassesItemsConstraintsContactTestBitMaskItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConstraintsContactTestBitMask}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConstraintsContactTestBitMaskAdapter() {
		if (graphicRootClassesItemsConstraintsContactTestBitMaskItemProvider == null) {
			graphicRootClassesItemsConstraintsContactTestBitMaskItemProvider = new GraphicRootClassesItemsConstraintsContactTestBitMaskItemProvider(this);
		}

		return graphicRootClassesItemsConstraintsContactTestBitMaskItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConnections} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConnectionsItemProvider graphicRootClassesItemsConnectionsItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConnections}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConnectionsAdapter() {
		if (graphicRootClassesItemsConnectionsItemProvider == null) {
			graphicRootClassesItemsConnectionsItemProvider = new GraphicRootClassesItemsConnectionsItemProvider(this);
		}

		return graphicRootClassesItemsConnectionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConnectionsItems} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConnectionsItemsItemProvider graphicRootClassesItemsConnectionsItemsItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConnectionsItems}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConnectionsItemsAdapter() {
		if (graphicRootClassesItemsConnectionsItemsItemProvider == null) {
			graphicRootClassesItemsConnectionsItemsItemProvider = new GraphicRootClassesItemsConnectionsItemsItemProvider(this);
		}

		return graphicRootClassesItemsConnectionsItemsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConnectionsItemsName} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConnectionsItemsNameItemProvider graphicRootClassesItemsConnectionsItemsNameItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConnectionsItemsName}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConnectionsItemsNameAdapter() {
		if (graphicRootClassesItemsConnectionsItemsNameItemProvider == null) {
			graphicRootClassesItemsConnectionsItemsNameItemProvider = new GraphicRootClassesItemsConnectionsItemsNameItemProvider(this);
		}

		return graphicRootClassesItemsConnectionsItemsNameItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConnectionsItemsType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConnectionsItemsTypeItemProvider graphicRootClassesItemsConnectionsItemsTypeItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConnectionsItemsType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConnectionsItemsTypeAdapter() {
		if (graphicRootClassesItemsConnectionsItemsTypeItemProvider == null) {
			graphicRootClassesItemsConnectionsItemsTypeItemProvider = new GraphicRootClassesItemsConnectionsItemsTypeItemProvider(this);
		}

		return graphicRootClassesItemsConnectionsItemsTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConnectionsItemsColor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConnectionsItemsColorItemProvider graphicRootClassesItemsConnectionsItemsColorItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConnectionsItemsColor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConnectionsItemsColorAdapter() {
		if (graphicRootClassesItemsConnectionsItemsColorItemProvider == null) {
			graphicRootClassesItemsConnectionsItemsColorItemProvider = new GraphicRootClassesItemsConnectionsItemsColorItemProvider(this);
		}

		return graphicRootClassesItemsConnectionsItemsColorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConnectionsItemsTextColor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConnectionsItemsTextColorItemProvider graphicRootClassesItemsConnectionsItemsTextColorItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConnectionsItemsTextColor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConnectionsItemsTextColorAdapter() {
		if (graphicRootClassesItemsConnectionsItemsTextColorItemProvider == null) {
			graphicRootClassesItemsConnectionsItemsTextColorItemProvider = new GraphicRootClassesItemsConnectionsItemsTextColorItemProvider(this);
		}

		return graphicRootClassesItemsConnectionsItemsTextColorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConnectionsItemsDecorator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConnectionsItemsDecoratorItemProvider graphicRootClassesItemsConnectionsItemsDecoratorItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConnectionsItemsDecorator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConnectionsItemsDecoratorAdapter() {
		if (graphicRootClassesItemsConnectionsItemsDecoratorItemProvider == null) {
			graphicRootClassesItemsConnectionsItemsDecoratorItemProvider = new GraphicRootClassesItemsConnectionsItemsDecoratorItemProvider(this);
		}

		return graphicRootClassesItemsConnectionsItemsDecoratorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConnectionsItemsDecoratorColor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConnectionsItemsDecoratorColorItemProvider graphicRootClassesItemsConnectionsItemsDecoratorColorItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConnectionsItemsDecoratorColor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConnectionsItemsDecoratorColorAdapter() {
		if (graphicRootClassesItemsConnectionsItemsDecoratorColorItemProvider == null) {
			graphicRootClassesItemsConnectionsItemsDecoratorColorItemProvider = new GraphicRootClassesItemsConnectionsItemsDecoratorColorItemProvider(this);
		}

		return graphicRootClassesItemsConnectionsItemsDecoratorColorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConnectionsItemsDecoratorWidth} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConnectionsItemsDecoratorWidthItemProvider graphicRootClassesItemsConnectionsItemsDecoratorWidthItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConnectionsItemsDecoratorWidth}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConnectionsItemsDecoratorWidthAdapter() {
		if (graphicRootClassesItemsConnectionsItemsDecoratorWidthItemProvider == null) {
			graphicRootClassesItemsConnectionsItemsDecoratorWidthItemProvider = new GraphicRootClassesItemsConnectionsItemsDecoratorWidthItemProvider(this);
		}

		return graphicRootClassesItemsConnectionsItemsDecoratorWidthItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConnectionsItemsDecoratorPos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConnectionsItemsDecoratorPosItemProvider graphicRootClassesItemsConnectionsItemsDecoratorPosItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConnectionsItemsDecoratorPos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConnectionsItemsDecoratorPosAdapter() {
		if (graphicRootClassesItemsConnectionsItemsDecoratorPosItemProvider == null) {
			graphicRootClassesItemsConnectionsItemsDecoratorPosItemProvider = new GraphicRootClassesItemsConnectionsItemsDecoratorPosItemProvider(this);
		}

		return graphicRootClassesItemsConnectionsItemsDecoratorPosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConnectionsItemsPattern} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConnectionsItemsPatternItemProvider graphicRootClassesItemsConnectionsItemsPatternItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConnectionsItemsPattern}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConnectionsItemsPatternAdapter() {
		if (graphicRootClassesItemsConnectionsItemsPatternItemProvider == null) {
			graphicRootClassesItemsConnectionsItemsPatternItemProvider = new GraphicRootClassesItemsConnectionsItemsPatternItemProvider(this);
		}

		return graphicRootClassesItemsConnectionsItemsPatternItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConnectionsItemsWidth} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConnectionsItemsWidthItemProvider graphicRootClassesItemsConnectionsItemsWidthItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConnectionsItemsWidth}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConnectionsItemsWidthAdapter() {
		if (graphicRootClassesItemsConnectionsItemsWidthItemProvider == null) {
			graphicRootClassesItemsConnectionsItemsWidthItemProvider = new GraphicRootClassesItemsConnectionsItemsWidthItemProvider(this);
		}

		return graphicRootClassesItemsConnectionsItemsWidthItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConnectionsItemsPosition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConnectionsItemsPositionItemProvider graphicRootClassesItemsConnectionsItemsPositionItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConnectionsItemsPosition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConnectionsItemsPositionAdapter() {
		if (graphicRootClassesItemsConnectionsItemsPositionItemProvider == null) {
			graphicRootClassesItemsConnectionsItemsPositionItemProvider = new GraphicRootClassesItemsConnectionsItemsPositionItemProvider(this);
		}

		return graphicRootClassesItemsConnectionsItemsPositionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link graphic.GraphicRootClassesItemsConnectionsItemsTarget} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GraphicRootClassesItemsConnectionsItemsTargetItemProvider graphicRootClassesItemsConnectionsItemsTargetItemProvider;

	/**
	 * This creates an adapter for a {@link graphic.GraphicRootClassesItemsConnectionsItemsTarget}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGraphicRootClassesItemsConnectionsItemsTargetAdapter() {
		if (graphicRootClassesItemsConnectionsItemsTargetItemProvider == null) {
			graphicRootClassesItemsConnectionsItemsTargetItemProvider = new GraphicRootClassesItemsConnectionsItemsTargetItemProvider(this);
		}

		return graphicRootClassesItemsConnectionsItemsTargetItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (graphicRootItemProvider != null) graphicRootItemProvider.dispose();
		if (graphicRootNameItemProvider != null) graphicRootNameItemProvider.dispose();
		if (graphicRootURIItemProvider != null) graphicRootURIItemProvider.dispose();
		if (graphicRootClassesItemProvider != null) graphicRootClassesItemProvider.dispose();
		if (graphicRootClassesItemsItemProvider != null) graphicRootClassesItemsItemProvider.dispose();
		if (graphicRootClassesItemsNameItemProvider != null) graphicRootClassesItemsNameItemProvider.dispose();
		if (graphicRootClassesItemsVersionsItemProvider != null) graphicRootClassesItemsVersionsItemProvider.dispose();
		if (graphicRootClassesItemsVersionsV1ItemProvider != null) graphicRootClassesItemsVersionsV1ItemProvider.dispose();
		if (graphicRootClassesItemsVersionsV2ItemProvider != null) graphicRootClassesItemsVersionsV2ItemProvider.dispose();
		if (graphicRootClassesItemsVersionsV3ItemProvider != null) graphicRootClassesItemsVersionsV3ItemProvider.dispose();
		if (graphicRootClassesItemsVnameItemProvider != null) graphicRootClassesItemsVnameItemProvider.dispose();
		if (graphicRootClassesItemsVnameV1ItemProvider != null) graphicRootClassesItemsVnameV1ItemProvider.dispose();
		if (graphicRootClassesItemsVnameV2ItemProvider != null) graphicRootClassesItemsVnameV2ItemProvider.dispose();
		if (graphicRootClassesItemsVnameV3ItemProvider != null) graphicRootClassesItemsVnameV3ItemProvider.dispose();
		if (graphicRootClassesItemsShowAttributesItemProvider != null) graphicRootClassesItemsShowAttributesItemProvider.dispose();
		if (graphicRootClassesItemsShowAttributesItemsItemProvider != null) graphicRootClassesItemsShowAttributesItemsItemProvider.dispose();
		if (graphicRootClassesItemsMaterialAttributesItemProvider != null) graphicRootClassesItemsMaterialAttributesItemProvider.dispose();
		if (graphicRootClassesItemsMaterialAttributesItemsItemProvider != null) graphicRootClassesItemsMaterialAttributesItemsItemProvider.dispose();
		if (graphicRootClassesItemsConstraintsItemProvider != null) graphicRootClassesItemsConstraintsItemProvider.dispose();
		if (graphicRootClassesItemsConstraintsPlanesItemProvider != null) graphicRootClassesItemsConstraintsPlanesItemProvider.dispose();
		if (graphicRootClassesItemsConstraintsIluminationItemProvider != null) graphicRootClassesItemsConstraintsIluminationItemProvider.dispose();
		if (graphicRootClassesItemsConstraintsSizeMaxItemProvider != null) graphicRootClassesItemsConstraintsSizeMaxItemProvider.dispose();
		if (graphicRootClassesItemsConstraintsSizeMinItemProvider != null) graphicRootClassesItemsConstraintsSizeMinItemProvider.dispose();
		if (graphicRootClassesItemsConstraintsSizeInitItemProvider != null) graphicRootClassesItemsConstraintsSizeInitItemProvider.dispose();
		if (graphicRootClassesItemsConstraintsOverlappingItemProvider != null) graphicRootClassesItemsConstraintsOverlappingItemProvider.dispose();
		if (graphicRootClassesItemsConstraintsXToOriginPosItemProvider != null) graphicRootClassesItemsConstraintsXToOriginPosItemProvider.dispose();
		if (graphicRootClassesItemsConstraintsYToOriginPosItemProvider != null) graphicRootClassesItemsConstraintsYToOriginPosItemProvider.dispose();
		if (graphicRootClassesItemsConstraintsZToOriginPosItemProvider != null) graphicRootClassesItemsConstraintsZToOriginPosItemProvider.dispose();
		if (graphicRootClassesItemsConstraintsRotationItemProvider != null) graphicRootClassesItemsConstraintsRotationItemProvider.dispose();
		if (graphicRootClassesItemsConstraintsTextItemProvider != null) graphicRootClassesItemsConstraintsTextItemProvider.dispose();
		if (graphicRootClassesItemsConstraintsTrimItemProvider != null) graphicRootClassesItemsConstraintsTrimItemProvider.dispose();
		if (graphicRootClassesItemsConstraintsCategoryBitMaskItemProvider != null) graphicRootClassesItemsConstraintsCategoryBitMaskItemProvider.dispose();
		if (graphicRootClassesItemsConstraintsCollisionBitMaskItemProvider != null) graphicRootClassesItemsConstraintsCollisionBitMaskItemProvider.dispose();
		if (graphicRootClassesItemsConstraintsContactTestBitMaskItemProvider != null) graphicRootClassesItemsConstraintsContactTestBitMaskItemProvider.dispose();
		if (graphicRootClassesItemsConnectionsItemProvider != null) graphicRootClassesItemsConnectionsItemProvider.dispose();
		if (graphicRootClassesItemsConnectionsItemsItemProvider != null) graphicRootClassesItemsConnectionsItemsItemProvider.dispose();
		if (graphicRootClassesItemsConnectionsItemsNameItemProvider != null) graphicRootClassesItemsConnectionsItemsNameItemProvider.dispose();
		if (graphicRootClassesItemsConnectionsItemsTypeItemProvider != null) graphicRootClassesItemsConnectionsItemsTypeItemProvider.dispose();
		if (graphicRootClassesItemsConnectionsItemsColorItemProvider != null) graphicRootClassesItemsConnectionsItemsColorItemProvider.dispose();
		if (graphicRootClassesItemsConnectionsItemsTextColorItemProvider != null) graphicRootClassesItemsConnectionsItemsTextColorItemProvider.dispose();
		if (graphicRootClassesItemsConnectionsItemsDecoratorItemProvider != null) graphicRootClassesItemsConnectionsItemsDecoratorItemProvider.dispose();
		if (graphicRootClassesItemsConnectionsItemsDecoratorColorItemProvider != null) graphicRootClassesItemsConnectionsItemsDecoratorColorItemProvider.dispose();
		if (graphicRootClassesItemsConnectionsItemsDecoratorWidthItemProvider != null) graphicRootClassesItemsConnectionsItemsDecoratorWidthItemProvider.dispose();
		if (graphicRootClassesItemsConnectionsItemsDecoratorPosItemProvider != null) graphicRootClassesItemsConnectionsItemsDecoratorPosItemProvider.dispose();
		if (graphicRootClassesItemsConnectionsItemsPatternItemProvider != null) graphicRootClassesItemsConnectionsItemsPatternItemProvider.dispose();
		if (graphicRootClassesItemsConnectionsItemsWidthItemProvider != null) graphicRootClassesItemsConnectionsItemsWidthItemProvider.dispose();
		if (graphicRootClassesItemsConnectionsItemsPositionItemProvider != null) graphicRootClassesItemsConnectionsItemsPositionItemProvider.dispose();
		if (graphicRootClassesItemsConnectionsItemsTargetItemProvider != null) graphicRootClassesItemsConnectionsItemsTargetItemProvider.dispose();
	}

}
