/*
 * generated by Xtext 2.23.0
 */
package accesses.accesses;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AccessesStandaloneSetup extends AccessesStandaloneSetupGenerated {

	public static void doSetup() {
		new AccessesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
