/*
 * generated by Xtext 2.23.0
 */
package accesses.accesses.ui;

import accesses.accesses.ui.internal.AccessesActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AccessesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(AccessesActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		AccessesActivator activator = AccessesActivator.getInstance();
		return activator != null ? activator.getInjector(AccessesActivator.ACCESSES_ACCESSES_ACCESSES) : null;
	}

}
