/*
 * generated by Xtext 2.23.0
 */
package codesinfos.codesinfos.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CodesinfosUiModule extends AbstractCodesinfosUiModule {

	public CodesinfosUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
