/*
 * generated by Xtext 2.23.0
 */
package accesses.accesses.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class AccessesUiModule extends AbstractAccessesUiModule {

	public AccessesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
