/*
 * generated by Xtext 2.23.0
 */
package codesinfos.codesinfos.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCodesinfosScopeProvider extends DelegatingScopeProvider {
}
