/**
 * generated by Xtext 2.23.0
 */
package accesses.accesses.formatting2;

import accesses.accesses.services.AccessesGrammarAccess;
import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class AccessesFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private AccessesGrammarAccess _accessesGrammarAccess;

  protected void _format(final /* AccessesRoot */Object accessesRoot, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\naccessesRoot cannot be resolved"
      + "\nformat cannot be resolved");
  }

  protected void _format(final /* AccessesRootExternalAccess */Object accessesRootExternalAccess, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nexternalAccess cannot be resolved"
      + "\nformat cannot be resolved");
  }

  public void format(final Object accessesRoot, final IFormattableDocument document) {
    if (accessesRoot instanceof XtextResource) {
      _format((XtextResource)accessesRoot, document);
      return;
    } else if (accessesRoot instanceof EObject) {
      _format((EObject)accessesRoot, document);
      return;
    } else if (accessesRoot == null) {
      _format((Void)null, document);
      return;
    } else if (accessesRoot != null) {
      _format(accessesRoot, document);
      return;
    } else if (accessesRoot != null) {
      _format(accessesRoot, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(accessesRoot, document).toString());
    }
  }
}
