/**
 * generated by Xtext 2.23.0
 */
package graphic.graphic.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(GraphicInjectorProvider.class)
@SuppressWarnings("all")
public class GraphicParsingTest {
  @Inject
  private /* ParseHelper<GraphicRoot> */Object parseHelper;

  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field GraphicParsingTest.parseHelper refers to the missing type GraphicRoot"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
