/*
 * generated by Xtext 2.23.0
 */
package ontological.ontological.ide;


/**
 * Use this class to register ide components.
 */
public class OntologicalIdeModule extends AbstractOntologicalIdeModule {
}
