/*
 * generated by Xtext 2.23.0
 */
package ontological.ontological.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOntologicalScopeProvider extends DelegatingScopeProvider {
}
