/*
 * generated by Xtext 2.23.0
 */
package ontological.ontological.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OntologicalAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ontological/ontological/parser/antlr/internal/InternalOntologicalParser.tokens");
	}
}
