/*
 * generated by Xtext 2.23.0
 */
package ontological.ontological.parser.antlr;

import com.google.inject.Inject;
import ontological.ontological.parser.antlr.internal.InternalOntologicalParser;
import ontological.ontological.services.OntologicalGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class OntologicalParser extends AbstractAntlrParser {

	@Inject
	private OntologicalGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOntologicalParser createParser(XtextTokenStream stream) {
		return new InternalOntologicalParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "OntologicalRoot";
	}

	public OntologicalGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OntologicalGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
