/**
 * generated by Xtext 2.23.0
 */
package codesinfos.codesinfos.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(CodesinfosInjectorProvider.class)
@SuppressWarnings("all")
public class CodesinfosParsingTest {
  @Inject
  private /* ParseHelper<CodesinfosRoot> */Object parseHelper;

  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field CodesinfosParsingTest.parseHelper refers to the missing type CodesinfosRoot"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
