/*
 * generated by Xtext 2.23.0
 */
package ontological.ontological;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class OntologicalStandaloneSetup extends OntologicalStandaloneSetupGenerated {

	public static void doSetup() {
		new OntologicalStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
