/**
 */
package codesinfos.provider;

import codesinfos.util.CodesinfosAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class CodesinfosItemProviderAdapterFactory extends CodesinfosAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public CodesinfosItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link codesinfos.CodesinfosRoot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CodesinfosRootItemProvider codesinfosRootItemProvider;

	/**
	 * This creates an adapter for a {@link codesinfos.CodesinfosRoot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCodesinfosRootAdapter() {
		if (codesinfosRootItemProvider == null) {
			codesinfosRootItemProvider = new CodesinfosRootItemProvider(this);
		}

		return codesinfosRootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link codesinfos.CodesinfosRootName} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CodesinfosRootNameItemProvider codesinfosRootNameItemProvider;

	/**
	 * This creates an adapter for a {@link codesinfos.CodesinfosRootName}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCodesinfosRootNameAdapter() {
		if (codesinfosRootNameItemProvider == null) {
			codesinfosRootNameItemProvider = new CodesinfosRootNameItemProvider(this);
		}

		return codesinfosRootNameItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link codesinfos.CodesinfosRootCodes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CodesinfosRootCodesItemProvider codesinfosRootCodesItemProvider;

	/**
	 * This creates an adapter for a {@link codesinfos.CodesinfosRootCodes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCodesinfosRootCodesAdapter() {
		if (codesinfosRootCodesItemProvider == null) {
			codesinfosRootCodesItemProvider = new CodesinfosRootCodesItemProvider(this);
		}

		return codesinfosRootCodesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link codesinfos.CodesinfosRootCodesItems} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CodesinfosRootCodesItemsItemProvider codesinfosRootCodesItemsItemProvider;

	/**
	 * This creates an adapter for a {@link codesinfos.CodesinfosRootCodesItems}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCodesinfosRootCodesItemsAdapter() {
		if (codesinfosRootCodesItemsItemProvider == null) {
			codesinfosRootCodesItemsItemProvider = new CodesinfosRootCodesItemsItemProvider(this);
		}

		return codesinfosRootCodesItemsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link codesinfos.CodesinfosRootCodesItemsName} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CodesinfosRootCodesItemsNameItemProvider codesinfosRootCodesItemsNameItemProvider;

	/**
	 * This creates an adapter for a {@link codesinfos.CodesinfosRootCodesItemsName}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCodesinfosRootCodesItemsNameAdapter() {
		if (codesinfosRootCodesItemsNameItemProvider == null) {
			codesinfosRootCodesItemsNameItemProvider = new CodesinfosRootCodesItemsNameItemProvider(this);
		}

		return codesinfosRootCodesItemsNameItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link codesinfos.CodesinfosRootCodesItemsClassname} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CodesinfosRootCodesItemsClassnameItemProvider codesinfosRootCodesItemsClassnameItemProvider;

	/**
	 * This creates an adapter for a {@link codesinfos.CodesinfosRootCodesItemsClassname}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCodesinfosRootCodesItemsClassnameAdapter() {
		if (codesinfosRootCodesItemsClassnameItemProvider == null) {
			codesinfosRootCodesItemsClassnameItemProvider = new CodesinfosRootCodesItemsClassnameItemProvider(this);
		}

		return codesinfosRootCodesItemsClassnameItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link codesinfos.CodesinfosRootCodesItemsNodename} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CodesinfosRootCodesItemsNodenameItemProvider codesinfosRootCodesItemsNodenameItemProvider;

	/**
	 * This creates an adapter for a {@link codesinfos.CodesinfosRootCodesItemsNodename}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCodesinfosRootCodesItemsNodenameAdapter() {
		if (codesinfosRootCodesItemsNodenameItemProvider == null) {
			codesinfosRootCodesItemsNodenameItemProvider = new CodesinfosRootCodesItemsNodenameItemProvider(this);
		}

		return codesinfosRootCodesItemsNodenameItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (codesinfosRootItemProvider != null) codesinfosRootItemProvider.dispose();
		if (codesinfosRootNameItemProvider != null) codesinfosRootNameItemProvider.dispose();
		if (codesinfosRootCodesItemProvider != null) codesinfosRootCodesItemProvider.dispose();
		if (codesinfosRootCodesItemsItemProvider != null) codesinfosRootCodesItemsItemProvider.dispose();
		if (codesinfosRootCodesItemsNameItemProvider != null) codesinfosRootCodesItemsNameItemProvider.dispose();
		if (codesinfosRootCodesItemsClassnameItemProvider != null) codesinfosRootCodesItemsClassnameItemProvider.dispose();
		if (codesinfosRootCodesItemsNodenameItemProvider != null) codesinfosRootCodesItemsNodenameItemProvider.dispose();
	}

}
