/*
 * generated by Xtext 2.23.0
 */
package graphic.graphic.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGraphicScopeProvider extends DelegatingScopeProvider {
}
