/*
 * generated by Xtext 2.23.0
 */
package graphic.graphic.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import graphic.graphic.GraphicRuntimeModule;
import graphic.graphic.GraphicStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GraphicIdeSetup extends GraphicStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GraphicRuntimeModule(), new GraphicIdeModule()));
	}
	
}
