/*
 * generated by Xtext 2.23.0
 */
package codesinfos.codesinfos;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CodesinfosStandaloneSetup extends CodesinfosStandaloneSetupGenerated {

	public static void doSetup() {
		new CodesinfosStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
