/*
 * generated by Xtext 2.23.0
 */
package graphic.graphic.parser.antlr;

import com.google.inject.Inject;
import graphic.graphic.parser.antlr.internal.InternalGraphicParser;
import graphic.graphic.services.GraphicGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GraphicParser extends AbstractAntlrParser {

	@Inject
	private GraphicGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGraphicParser createParser(XtextTokenStream stream) {
		return new InternalGraphicParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GraphicRoot";
	}

	public GraphicGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GraphicGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
