/*
 * generated by Xtext 2.23.0
 */
package graphic.graphic.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GraphicAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("graphic/graphic/parser/antlr/internal/InternalGraphicParser.tokens");
	}
}
