/*
 * generated by Xtext 2.23.0
 */
package graphic.graphic.ui.tests;

import com.google.inject.Injector;
import graphic.graphic.ui.internal.GraphicActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GraphicUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GraphicActivator.getInstance().getInjector("graphic.graphic.Graphic");
	}

}
